apis for ip blocking and ip filtering
CiscoUcs/imcsdk pull request #105
Opened 2017-02-07 08:56 UTC by waghswapnil

- apis for ip blocking and ip filtering
- skip params with 'None' value during 'check prop match'

Signed-off-by: Swapnil Wagh <waghswapnil@gmail.com>

2017-02-07 15:56 UTC, parag-may4 commented on imcsdk/apis/admin/ip.py
> +def is_ip_blocking_enabled(handle,):
+def is_ip_blocking_enabled(handle,):  -> extra ','

2017-02-07 15:57 UTC, parag-may4 commented on imcsdk/apis/admin/ip.py
> +
Can be directly **kwarags in check_prop_match instead of making dictionary.

2017-02-07 16:00 UTC, parag-may4 commented on imcsdk/apis/admin/ip.py
> +
Good to add warning message as this will logout the existing user and not allow any other IP to login. Also applicable for modify case.

2017-02-07 16:04 UTC, parag-may4 commented
LGTM [ fix this: def is_ip_blocking_enabled(handle,): ]

2017-02-08 00:41 UTC, vvb commented on imcsdk/apis/admin/ip.py
> +def is_ip_blocking_enabled(handle,):
nice catch. @waghswapnil how did vim not highlight this in red?

2017-02-08 00:49 UTC, vvb commented on imcsdk/apis/admin/ip.py
> +    """
@waghswapnil this API is slightly confusing when it comes to param types.. 

the defaults specified are ints..
```
def ip_blocking_enable(handle, fail_count=5, fail_window=60, penalty_time=300, **kwargs):
```

the docstring says `str`
```
       fail_count (str): Number of times a user can attempt to log in
 +                          unsuccessfully, before the system locks that user out
 +                          Range [3-10] attempts
 +        fail_window (str): Length of time, in seconds, in which the
 +                           unsuccessful login attempts must occur in order
 +                           for the user to be locked out.
 +                           Range [60-120] seconds
 +        penalty_time (str): The number of seconds the user remains locked out.
 +                            Range [300-900] seconds
```

the example specifies them as `str`
```
+        ip_blocking_enable(handle, fail_count='6',
+                           fail_window='120', penalty_time='800')
```
when forming args internally we don't do `str()`.  We should clean this up for this and other APIs(if so).

The exists function also assumes `str`.

2017-02-08 00:50 UTC, vvb requested changes
check comments

2017-02-08 01:55 UTC, waghswapnil commented on imcsdk/apis/admin/ip.py
> +
warning messages have been added already. please check the recent commit

2017-02-08 01:58 UTC, waghswapnil commented on imcsdk/apis/admin/ip.py
> +    """
done

2017-02-08 02:04 UTC, vvb approved these changes
LGTM

2017-02-08 02:04 UTC, merged