Update imcsession.py
CiscoUcs/imcsdk pull request #228
Opened 2022-02-20 04:46 UTC by ecoen66

Added support for DNA Center and CNR appliances.  Added allowance for ancient IMC firmware.

2023-11-27 06:43 UTC, vvb commented on setup.py
> +    name='imcsdk_ecoen66',
Changes in setup.py need to be reverted for this to be merged.

2023-11-27 06:44 UTC, vvb requested changes
please revert changes done in setup.py

2023-12-13 02:34 UTC, ecoen66 reviewed
Changes removed from setup.py

2023-12-13 02:39 UTC, ecoen66 reviewed
Added DN3 DNAC

2023-12-13 04:31 UTC, vvb approved these changes
LGTM

2023-12-13 04:31 UTC, merged