Update power tests
CiscoUcs/imcsdk pull request #36
Opened 2016-09-16 21:04 UTC by britthouser

This PR is a follow on to #33 which includes tests for those functions.  I added some developer info into CONTRIBUTIONS.rst to show how to run tests and updated requirements_dev.txt to include nose and mock to be able to run those tests.  I did some code cleanup, and then added a set of tests utilizing mock instead of real hardware.

2016-09-19 05:05 UTC, vvb commented on tests/server/test_mock_power.py
> +#
@britthouser yet to go through the test itself.. but I think we should create a new hierarchy for unit-tests.. `tests/unit-tests/*`. so this particular file should be `tests/unit-tests/server/power.py`. Anything under `unit-tests` should never need a live connection.. let us do away with test or mock in the file name too.

2016-09-19 05:05 UTC, vvb commented on CONTRIBUTING.rst
> +
+1. Thanks for adding this here.

2016-09-19 05:06 UTC, vvb requested changes

2016-09-19 05:06 UTC, vvb commented on tests/connection/connection.cfg
> -[imc]
@britthouser let us not delete this file. Let the file exist with the same content that exists today. This would open us up to possible syntax and typos from users.

I agree, that we should add it to .gitignore, so that local changes are not pushed.

2016-09-19 06:43 UTC, vvb commented
@britthouser thanks for adding tests that use the mock library.. we need them badly..
I am good with all the changes minus the comments.

2016-09-19 18:29 UTC, britthouser commented on tests/connection/connection.cfg
> -[imc]
Its the adding to the .gitignore that also deletes it as part of the commit.  I'm not sure we can do one without the other?

2016-09-19 18:30 UTC, britthouser commented on tests/server/test_mock_power.py
> +#
Done.

2016-09-21 03:40 UTC, vvb commented on tests/connection/connection.cfg
> -[imc]
@britthouser so i looked this up. I think a better way to do this, is not to add this in `.gitignore`, and ask git to not check this for changes separately..

2016-09-21 03:44 UTC, vvb commented
@britthouser thanks for taking care of the comments. really appreciate you taking the time to work on this PR. I will merge this now.

2016-09-21 03:45 UTC, merged

2016-09-21 10:59 UTC, britthouser commented on tests/connection/connection.cfg
> -[imc]
Ok.  That sounds like something each developer would need todo locally?  I can make a new patch that adds this file in, and then adds that command to the CONTRIBUTIONS.rst section that talks about running tests.  Sound good?