Implement IPMI enable and disable functions.
CiscoUcs/imcsdk pull request #40
Opened 2016-09-23 11:04 UTC by britthouser

This commit adds the apis/admin/communication_services.py
module with functions to both enable and disable IPMI.

Signed-off-by: Britt Houser <bhouser@cisco.com>

2016-09-23 11:05 UTC, britthouser commented
This implements #39

2016-09-23 16:22 UTC, vvb commented on imcsdk/apis/admin/communication_services.py
> +# Copyright 2016 Cisco Systems, Inc.
@britthouser the code looks good. Can we not call this `communication_services.py`. On the UCSM UI, "communication services" refers to many other things. let us just call it `ipmi.py`

2016-09-23 16:24 UTC, britthouser commented
My thought was that eventually we could add function for the other services as well?  Its up to you though, I can easily rename it.

2016-09-23 16:24 UTC, vvb commented on imcsdk/apis/admin/communication_services.py
> +    :param priv: Optional privilege level: 'admin', 'user', 'read-only'
the docstring format we follow is slightly different.. can you look it up in the other files and try to use the same.

2016-09-23 16:24 UTC, vvb requested changes
LGTM, other than minor comments.

2016-09-23 16:26 UTC, vvb commented
@britthouser apis folder, I think many smaller files is better than many large ones.. so let us just call it `ipmi.py` and be done right now.

2016-09-23 16:34 UTC, britthouser commented on imcsdk/apis/admin/communication_services.py
> +    :param priv: Optional privilege level: 'admin', 'user', 'read-only'
Doh...forget to change that when I reworked my other code.  Fixing...

2016-09-23 16:40 UTC, britthouser commented on imcsdk/apis/admin/communication_services.py
> +    :param priv: Optional privilege level: 'admin', 'user', 'read-only'
done!

2016-09-23 16:40 UTC, britthouser commented
Ok I renamed to ipmi.py and amended commit.

2016-10-12 05:05 UTC, vvb approved these changes

2016-10-12 05:05 UTC, merged